version: 2

builds:
  - id: gh-problemas
    main: .
    binary: gh-problemas
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/cboone/gh-problemas/cmd.version={{.Version}}

archives:
  - ids:
      - gh-problemas
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: cboone
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/cboone/gh-problemas"
    description: "TUI for GitHub issue management"
    license: MIT
    dependencies:
      - name: gh
    test: |
      assert_match version.to_s, shell_output("#{bin}/gh-problemas --version")
