name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: cboone/gh-actions/.github/workflows/go-ci.yml@v2
    with:
      run-lint: true
      run-format-check: true
